/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangResultadosRouteImport } from './routes/$lang.resultados'
import { Route as LangProyectoRouteImport } from './routes/$lang.proyecto'
import { Route as LangPrivacidadRouteImport } from './routes/$lang.privacidad'
import { Route as LangMaterialesRouteImport } from './routes/$lang.materiales'
import { Route as LangCookiesRouteImport } from './routes/$lang.cookies'
import { Route as LangContactoRouteImport } from './routes/$lang.contacto'
import { Route as LangConsorcioRouteImport } from './routes/$lang.consorcio'
import { Route as LangAvisoLegalRouteImport } from './routes/$lang.aviso-legal'
import { Route as LangActividadesRouteImport } from './routes/$lang.actividades'
import { Route as LangActualidadIndexRouteImport } from './routes/$lang.actualidad.index'
import { Route as LangActualidadSlugRouteImport } from './routes/$lang.actualidad.$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangResultadosRoute = LangResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => LangRoute,
} as any)
const LangProyectoRoute = LangProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacidadRoute = LangPrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => LangRoute,
} as any)
const LangMaterialesRoute = LangMaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => LangRoute,
} as any)
const LangCookiesRoute = LangCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LangRoute,
} as any)
const LangContactoRoute = LangContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => LangRoute,
} as any)
const LangConsorcioRoute = LangConsorcioRouteImport.update({
  id: '/consorcio',
  path: '/consorcio',
  getParentRoute: () => LangRoute,
} as any)
const LangAvisoLegalRoute = LangAvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => LangRoute,
} as any)
const LangActividadesRoute = LangActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => LangRoute,
} as any)
const LangActualidadIndexRoute = LangActualidadIndexRouteImport.update({
  id: '/actualidad/',
  path: '/actualidad/',
  getParentRoute: () => LangRoute,
} as any)
const LangActualidadSlugRoute = LangActualidadSlugRouteImport.update({
  id: '/actualidad/$slug',
  path: '/actualidad/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/actividades': typeof LangActividadesRoute
  '/$lang/aviso-legal': typeof LangAvisoLegalRoute
  '/$lang/consorcio': typeof LangConsorcioRoute
  '/$lang/contacto': typeof LangContactoRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/materiales': typeof LangMaterialesRoute
  '/$lang/privacidad': typeof LangPrivacidadRoute
  '/$lang/proyecto': typeof LangProyectoRoute
  '/$lang/resultados': typeof LangResultadosRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/actualidad/$slug': typeof LangActualidadSlugRoute
  '/$lang/actualidad/': typeof LangActualidadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/actividades': typeof LangActividadesRoute
  '/$lang/aviso-legal': typeof LangAvisoLegalRoute
  '/$lang/consorcio': typeof LangConsorcioRoute
  '/$lang/contacto': typeof LangContactoRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/materiales': typeof LangMaterialesRoute
  '/$lang/privacidad': typeof LangPrivacidadRoute
  '/$lang/proyecto': typeof LangProyectoRoute
  '/$lang/resultados': typeof LangResultadosRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/actualidad/$slug': typeof LangActualidadSlugRoute
  '/$lang/actualidad': typeof LangActualidadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/actividades': typeof LangActividadesRoute
  '/$lang/aviso-legal': typeof LangAvisoLegalRoute
  '/$lang/consorcio': typeof LangConsorcioRoute
  '/$lang/contacto': typeof LangContactoRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/materiales': typeof LangMaterialesRoute
  '/$lang/privacidad': typeof LangPrivacidadRoute
  '/$lang/proyecto': typeof LangProyectoRoute
  '/$lang/resultados': typeof LangResultadosRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/actualidad/$slug': typeof LangActualidadSlugRoute
  '/$lang/actualidad/': typeof LangActualidadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/actividades'
    | '/$lang/aviso-legal'
    | '/$lang/consorcio'
    | '/$lang/contacto'
    | '/$lang/cookies'
    | '/$lang/materiales'
    | '/$lang/privacidad'
    | '/$lang/proyecto'
    | '/$lang/resultados'
    | '/$lang/'
    | '/$lang/actualidad/$slug'
    | '/$lang/actualidad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/actividades'
    | '/$lang/aviso-legal'
    | '/$lang/consorcio'
    | '/$lang/contacto'
    | '/$lang/cookies'
    | '/$lang/materiales'
    | '/$lang/privacidad'
    | '/$lang/proyecto'
    | '/$lang/resultados'
    | '/$lang'
    | '/$lang/actualidad/$slug'
    | '/$lang/actualidad'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/actividades'
    | '/$lang/aviso-legal'
    | '/$lang/consorcio'
    | '/$lang/contacto'
    | '/$lang/cookies'
    | '/$lang/materiales'
    | '/$lang/privacidad'
    | '/$lang/proyecto'
    | '/$lang/resultados'
    | '/$lang/'
    | '/$lang/actualidad/$slug'
    | '/$lang/actualidad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/resultados': {
      id: '/$lang/resultados'
      path: '/resultados'
      fullPath: '/$lang/resultados'
      preLoaderRoute: typeof LangResultadosRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/proyecto': {
      id: '/$lang/proyecto'
      path: '/proyecto'
      fullPath: '/$lang/proyecto'
      preLoaderRoute: typeof LangProyectoRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacidad': {
      id: '/$lang/privacidad'
      path: '/privacidad'
      fullPath: '/$lang/privacidad'
      preLoaderRoute: typeof LangPrivacidadRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/materiales': {
      id: '/$lang/materiales'
      path: '/materiales'
      fullPath: '/$lang/materiales'
      preLoaderRoute: typeof LangMaterialesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cookies': {
      id: '/$lang/cookies'
      path: '/cookies'
      fullPath: '/$lang/cookies'
      preLoaderRoute: typeof LangCookiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contacto': {
      id: '/$lang/contacto'
      path: '/contacto'
      fullPath: '/$lang/contacto'
      preLoaderRoute: typeof LangContactoRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/consorcio': {
      id: '/$lang/consorcio'
      path: '/consorcio'
      fullPath: '/$lang/consorcio'
      preLoaderRoute: typeof LangConsorcioRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/aviso-legal': {
      id: '/$lang/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/$lang/aviso-legal'
      preLoaderRoute: typeof LangAvisoLegalRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/actividades': {
      id: '/$lang/actividades'
      path: '/actividades'
      fullPath: '/$lang/actividades'
      preLoaderRoute: typeof LangActividadesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/actualidad/': {
      id: '/$lang/actualidad/'
      path: '/actualidad'
      fullPath: '/$lang/actualidad/'
      preLoaderRoute: typeof LangActualidadIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/actualidad/$slug': {
      id: '/$lang/actualidad/$slug'
      path: '/actualidad/$slug'
      fullPath: '/$lang/actualidad/$slug'
      preLoaderRoute: typeof LangActualidadSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangActividadesRoute: typeof LangActividadesRoute
  LangAvisoLegalRoute: typeof LangAvisoLegalRoute
  LangConsorcioRoute: typeof LangConsorcioRoute
  LangContactoRoute: typeof LangContactoRoute
  LangCookiesRoute: typeof LangCookiesRoute
  LangMaterialesRoute: typeof LangMaterialesRoute
  LangPrivacidadRoute: typeof LangPrivacidadRoute
  LangProyectoRoute: typeof LangProyectoRoute
  LangResultadosRoute: typeof LangResultadosRoute
  LangIndexRoute: typeof LangIndexRoute
  LangActualidadSlugRoute: typeof LangActualidadSlugRoute
  LangActualidadIndexRoute: typeof LangActualidadIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangActividadesRoute: LangActividadesRoute,
  LangAvisoLegalRoute: LangAvisoLegalRoute,
  LangConsorcioRoute: LangConsorcioRoute,
  LangContactoRoute: LangContactoRoute,
  LangCookiesRoute: LangCookiesRoute,
  LangMaterialesRoute: LangMaterialesRoute,
  LangPrivacidadRoute: LangPrivacidadRoute,
  LangProyectoRoute: LangProyectoRoute,
  LangResultadosRoute: LangResultadosRoute,
  LangIndexRoute: LangIndexRoute,
  LangActualidadSlugRoute: LangActualidadSlugRoute,
  LangActualidadIndexRoute: LangActualidadIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
